export const ACTIVITY_CATEGORIES = [
  "Movies 🎬",
  "Sports ⚽",
  "Food 🍕",
  "Travel ✈️",
  "Music 🎵",
  "Fitness 🏋️",
  "Shopping 🛍️",
  "Events 🎉",
  "Study 📚",
  "Gaming 🎮",
  "Hangouts 👫",
  "Art & Culture 🎨",
  "Entertainment 🎭",
  "Party 🥳",
  "Social 🤝",
  "Religious 🕉️",
  "Tech 💻",
  "Startups 🚀",
  "Career 💼",
  "Wellness 🧘",
  "Photography 📸",
  "Books 📖",
  "Fashion 👗",
  "Comedy 😂",
  "Foodie 🍔",
  "Campus 🎓",
  "Lifestyle 🌿",
  "Music & Dance 💃",
] as const;

export type ActivityCategory = typeof ACTIVITY_CATEGORIES[number];
